//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPizzaShop.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pw {
            get {
                return this.PwField;
            }
            set {
                if ((object.ReferenceEquals(this.PwField, value) != true)) {
                    this.PwField = value;
                    this.RaisePropertyChanged("Pw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UName {
            get {
                return this.UNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UNameField, value) != true)) {
                    this.UNameField = value;
                    this.RaisePropertyChanged("UName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authentication", ReplyAction="http://tempuri.org/IService/AuthenticationResponse")]
        string Authentication(MyPizzaShop.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authentication", ReplyAction="http://tempuri.org/IService/AuthenticationResponse")]
        System.Threading.Tasks.Task<string> AuthenticationAsync(MyPizzaShop.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PizzaList", ReplyAction="http://tempuri.org/IService/PizzaListResponse")]
        string[][] PizzaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PizzaList", ReplyAction="http://tempuri.org/IService/PizzaListResponse")]
        System.Threading.Tasks.Task<string[][]> PizzaListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MyPizzaShop.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MyPizzaShop.ServiceReference.IService>, MyPizzaShop.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authentication(MyPizzaShop.ServiceReference.User user) {
            return base.Channel.Authentication(user);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticationAsync(MyPizzaShop.ServiceReference.User user) {
            return base.Channel.AuthenticationAsync(user);
        }
        
        public string[][] PizzaList() {
            return base.Channel.PizzaList();
        }
        
        public System.Threading.Tasks.Task<string[][]> PizzaListAsync() {
            return base.Channel.PizzaListAsync();
        }
    }
}
